package models;
// Generated 15 mai 2022 15:03:36 by Hibernate Tools 3.6.0.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * Administrateur generated by hbm2java
 */
@Entity
@Table(name = "administrateur", schema = "public")
public class Administrateur implements java.io.Serializable {

	private int id;
	private Personne personne;
	private Integer codepin;

	public Administrateur() {
	}

	public Administrateur(Personne personne) {
		this.personne = personne;
	}

	public Administrateur(Personne personne, Integer codepin) {
		this.personne = personne;
		this.codepin = codepin;
	}

	@GenericGenerator(name = "generator", strategy = "foreign", parameters = @Parameter(name = "property", value = "personne"))
	@Id
	@GeneratedValue(generator = "generator")

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@PrimaryKeyJoinColumn
	public Personne getPersonne() {
		return this.personne;
	}

	public void setPersonne(Personne personne) {
		this.personne = personne;
	}

	@Column(name = "codepin")
	public Integer getCodepin() {
		return this.codepin;
	}

	public void setCodepin(Integer codepin) {
		this.codepin = codepin;
	}

}
