package models;
// Generated 15 mai 2022 15:03:36 by Hibernate Tools 3.6.0.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Bien generated by hbm2java
 */
@Entity
@Table(name = "bien", schema = "public")
public class Bien implements java.io.Serializable {

	private int id;
	private Elementbien elementbien;
	private Integer nombien;
	private Set<Service> services = new HashSet<Service>(0);
	private Set<Service> services_1 = new HashSet<Service>(0);

	public Bien() {
	}

	public Bien(int id, Elementbien elementbien) {
		this.id = id;
		this.elementbien = elementbien;
	}

	public Bien(int id, Elementbien elementbien, Integer nombien, Set<Service> services, Set<Service> services_1) {
		this.id = id;
		this.elementbien = elementbien;
		this.nombien = nombien;
		this.services = services;
		this.services_1 = services_1;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ele_id", nullable = false)
	public Elementbien getElementbien() {
		return this.elementbien;
	}

	public void setElementbien(Elementbien elementbien) {
		this.elementbien = elementbien;
	}

	@Column(name = "nombien")
	public Integer getNombien() {
		return this.nombien;
	}

	public void setNombien(Integer nombien) {
		this.nombien = nombien;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "bien")
	public Set<Service> getServices() {
		return this.services;
	}

	public void setServices(Set<Service> services) {
		this.services = services;
	}

	@ManyToMany(fetch = FetchType.LAZY, mappedBy = "biens")
	public Set<Service> getServices_1() {
		return this.services_1;
	}

	public void setServices_1(Set<Service> services_1) {
		this.services_1 = services_1;
	}

}
