package models;
// Generated 15 mai 2022 15:03:36 by Hibernate Tools 3.6.0.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Depense generated by hbm2java
 */
@Entity
@Table(name = "depense", schema = "public")
public class Depense implements java.io.Serializable {

	private int numdepense;
	private Rapport rapport;
	private Integer montanrdepense;

	public Depense() {
	}

	public Depense(int numdepense, Rapport rapport) {
		this.numdepense = numdepense;
		this.rapport = rapport;
	}

	public Depense(int numdepense, Rapport rapport, Integer montanrdepense) {
		this.numdepense = numdepense;
		this.rapport = rapport;
		this.montanrdepense = montanrdepense;
	}

	@Id

	@Column(name = "numdepense", unique = true, nullable = false)
	public int getNumdepense() {
		return this.numdepense;
	}

	public void setNumdepense(int numdepense) {
		this.numdepense = numdepense;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id", nullable = false)
	public Rapport getRapport() {
		return this.rapport;
	}

	public void setRapport(Rapport rapport) {
		this.rapport = rapport;
	}

	@Column(name = "montanrdepense")
	public Integer getMontanrdepense() {
		return this.montanrdepense;
	}

	public void setMontanrdepense(Integer montanrdepense) {
		this.montanrdepense = montanrdepense;
	}

}
