package models;
// Generated 15 mai 2022 15:03:36 by Hibernate Tools 3.6.0.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * DetailbienId generated by hbm2java
 */
@Embeddable
public class DetailbienId implements java.io.Serializable {

	private int eleId;
	private int id;

	public DetailbienId() {
	}

	public DetailbienId(int eleId, int id) {
		this.eleId = eleId;
		this.id = id;
	}

	@Column(name = "ele_id", nullable = false)
	public int getEleId() {
		return this.eleId;
	}

	public void setEleId(int eleId) {
		this.eleId = eleId;
	}

	@Column(name = "id", nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof DetailbienId))
			return false;
		DetailbienId castOther = (DetailbienId) other;

		return (this.getEleId() == castOther.getEleId()) && (this.getId() == castOther.getId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getEleId();
		result = 37 * result + this.getId();
		return result;
	}

}
