package models;
// Generated 15 mai 2022 15:03:36 by Hibernate Tools 3.6.0.Final

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Detailbien generated by hbm2java
 */
@Entity
@Table(name = "detailbien", schema = "public")
public class Detailbien implements java.io.Serializable {

	private DetailbienId id;
	private Personne personne;
	private Elementbien elementbien;
	private Integer prix;
	private Date datedebut;
	private Date datefin;

	public Detailbien() {
	}

	public Detailbien(DetailbienId id, Personne personne, Elementbien elementbien) {
		this.id = id;
		this.personne = personne;
		this.elementbien = elementbien;
	}

	public Detailbien(DetailbienId id, Personne personne, Elementbien elementbien, Integer prix, Date datedebut,
			Date datefin) {
		this.id = id;
		this.personne = personne;
		this.elementbien = elementbien;
		this.prix = prix;
		this.datedebut = datedebut;
		this.datefin = datefin;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "eleId", column = @Column(name = "ele_id", nullable = false)),
			@AttributeOverride(name = "id", column = @Column(name = "id", nullable = false)) })
	public DetailbienId getId() {
		return this.id;
	}

	public void setId(DetailbienId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id", nullable = false, insertable = false, updatable = false)
	public Personne getPersonne() {
		return this.personne;
	}

	public void setPersonne(Personne personne) {
		this.personne = personne;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ele_id", nullable = false, insertable = false, updatable = false)
	public Elementbien getElementbien() {
		return this.elementbien;
	}

	public void setElementbien(Elementbien elementbien) {
		this.elementbien = elementbien;
	}

	@Column(name = "prix")
	public Integer getPrix() {
		return this.prix;
	}

	public void setPrix(Integer prix) {
		this.prix = prix;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "datedebut", length = 13)
	public Date getDatedebut() {
		return this.datedebut;
	}

	public void setDatedebut(Date datedebut) {
		this.datedebut = datedebut;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "datefin", length = 13)
	public Date getDatefin() {
		return this.datefin;
	}

	public void setDatefin(Date datefin) {
		this.datefin = datefin;
	}

}
