package models;
// Generated 15 mai 2022 15:03:36 by Hibernate Tools 3.6.0.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Message generated by hbm2java
 */
@Entity
@Table(name = "message", schema = "public")
public class Message implements java.io.Serializable {

	private int id;
	private Personne personne;
	private Integer emetteur;
	private Integer destinataire;
	private Date dateenvoi;
	private String objet;
	private String reponse;
	private Date datelu;
	private Date datereponse;

	public Message() {
	}

	public Message(int id, Personne personne) {
		this.id = id;
		this.personne = personne;
	}

	public Message(int id, Personne personne, Integer emetteur, Integer destinataire, Date dateenvoi, String objet,
			String reponse, Date datelu, Date datereponse) {
		this.id = id;
		this.personne = personne;
		this.emetteur = emetteur;
		this.destinataire = destinataire;
		this.dateenvoi = dateenvoi;
		this.objet = objet;
		this.reponse = reponse;
		this.datelu = datelu;
		this.datereponse = datereponse;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "per_id", nullable = false)
	public Personne getPersonne() {
		return this.personne;
	}

	public void setPersonne(Personne personne) {
		this.personne = personne;
	}

	@Column(name = "emetteur")
	public Integer getEmetteur() {
		return this.emetteur;
	}

	public void setEmetteur(Integer emetteur) {
		this.emetteur = emetteur;
	}

	@Column(name = "destinataire")
	public Integer getDestinataire() {
		return this.destinataire;
	}

	public void setDestinataire(Integer destinataire) {
		this.destinataire = destinataire;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "dateenvoi", length = 13)
	public Date getDateenvoi() {
		return this.dateenvoi;
	}

	public void setDateenvoi(Date dateenvoi) {
		this.dateenvoi = dateenvoi;
	}

	@Column(name = "objet", length = 254)
	public String getObjet() {
		return this.objet;
	}

	public void setObjet(String objet) {
		this.objet = objet;
	}

	@Column(name = "reponse", length = 254)
	public String getReponse() {
		return this.reponse;
	}

	public void setReponse(String reponse) {
		this.reponse = reponse;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "datelu", length = 13)
	public Date getDatelu() {
		return this.datelu;
	}

	public void setDatelu(Date datelu) {
		this.datelu = datelu;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "datereponse", length = 13)
	public Date getDatereponse() {
		return this.datereponse;
	}

	public void setDatereponse(Date datereponse) {
		this.datereponse = datereponse;
	}

}
