package models;
// Generated 15 mai 2022 15:03:36 by Hibernate Tools 3.6.0.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Pays generated by hbm2java
 */
@Entity
@Table(name = "pays", schema = "public")
public class Pays implements java.io.Serializable {

	private int id;
	private String nomays;
	private Set<Region> regions = new HashSet<Region>(0);

	public Pays() {
	}

	public Pays(int id) {
		this.id = id;
	}

	public Pays(int id, String nomays, Set<Region> regions) {
		this.id = id;
		this.nomays = nomays;
		this.regions = regions;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "nomays", length = 254)
	public String getNomays() {
		return this.nomays;
	}

	public void setNomays(String nomays) {
		this.nomays = nomays;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "pays")
	public Set<Region> getRegions() {
		return this.regions;
	}

	public void setRegions(Set<Region> regions) {
		this.regions = regions;
	}

}
