package models;
// Generated 15 mai 2022 15:03:36 by Hibernate Tools 3.6.0.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.Table;

/**
 * Personne generated by hbm2java
 */
@Entity
@Table(name = "personne", schema = "public")
public class Personne implements java.io.Serializable {

	private int id;
	private String nom;
	private String prenom;
	private String login;
	private String password;
	private String telephone;
	private Integer cin;
	private String role;
	private Integer status;
	//private Client client;
	//private Set<Detailbien> detailbiens = new HashSet<Detailbien>(0);
	//private Gerant gerant;
	//private Entrepreneur entrepreneur;
	//private Set<Message> messages = new HashSet<Message>(0);
	//private Administrateur administrateur;

	public Personne() {
	}

	public Personne(int id) {
		this.id = id;
	}

	/*public Personne(int id, String nom, String prenom, String login, String password, String telephone, Integer cin,
			String role, Client client, Set<Detailbien> detailbiens, Gerant gerant, Entrepreneur entrepreneur,
			Set<Message> messages, Administrateur administrateur) {
		this.id = id;
		this.nom = nom;
		this.prenom = prenom;
		this.login = login;
		this.password = password;
		this.telephone = telephone;
		this.cin = cin;
		this.role = role;
		this.client = client;
		this.detailbiens = detailbiens;
		this.gerant = gerant;
		this.entrepreneur = entrepreneur;
		this.messages = messages;
		this.administrateur = administrateur;
	}
	*/

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "nom", length = 254)
	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	@Column(name = "prenom", length = 254)
	public String getPrenom() {
		return this.prenom;
	}

	public void setPrenom(String prenom) {
		this.prenom = prenom;
	}

	@Column(name = "login", length = 254)
	public String getLogin() {
		return this.login;
	}

	public void setLogin(String login) {
		this.login = login;
	}

	@Column(name = "password", length = 254)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "telephone", length = 254)
	public String getTelephone() {
		return this.telephone;
	}

	public void setTelephone(String telephone) {
		this.telephone = telephone;
	}

	@Column(name = "cin")
	public Integer getCin() {
		return this.cin;
	}

	public void setCin(Integer cin) {
		this.cin = cin;
	}

	public Personne(int id, String nom, String prenom, String login, String password, String telephone, Integer cin,
			String role) {
		super();
		this.id = id;
		this.nom = nom;
		this.prenom = prenom;
		this.login = login;
		this.password = password;
		this.telephone = telephone;
		this.cin = cin;
		this.role = role;
	}

	@Column(name = "role", length = 254)
	public String getRole() {
		return this.role;
	}

	public void setRole(String role) {
		this.role = role;
	}

	public Integer getStatus() {
		return status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}
	
/*
	@OneToOne(fetch = FetchType.LAZY, mappedBy = "personne")
	public Client getClient() {
		return this.client;
	}

	public void setClient(Client client) {
		this.client = client;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "personne")
	public Set<Detailbien> getDetailbiens() {
		return this.detailbiens;
	}

	public void setDetailbiens(Set<Detailbien> detailbiens) {
		this.detailbiens = detailbiens;
	}

	@OneToOne(fetch = FetchType.LAZY, mappedBy = "personne")
	public Gerant getGerant() {
		return this.gerant;
	}

	public void setGerant(Gerant gerant) {
		this.gerant = gerant;
	}

	@OneToOne(fetch = FetchType.LAZY, mappedBy = "personne")
	public Entrepreneur getEntrepreneur() {
		return this.entrepreneur;
	}

	public void setEntrepreneur(Entrepreneur entrepreneur) {
		this.entrepreneur = entrepreneur;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "personne")
	public Set<Message> getMessages() {
		return this.messages;
	}

	public void setMessages(Set<Message> messages) {
		this.messages = messages;
	}

	@OneToOne(fetch = FetchType.LAZY, mappedBy = "personne")
	public Administrateur getAdministrateur() {
		return this.administrateur;
	}

	public void setAdministrateur(Administrateur administrateur) {
		this.administrateur = administrateur;
	}
           */
}
