package models;
// Generated 15 mai 2022 15:03:36 by Hibernate Tools 3.6.0.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Profil generated by hbm2java
 */
@Entity
@Table(name = "profil", schema = "public")
public class Profil implements java.io.Serializable {

	private int id;
	private Client client;
	private String nomprofil;

	public Profil() {
	}

	public Profil(int id, Client client) {
		this.id = id;
		this.client = client;
	}

	public Profil(int id, Client client, String nomprofil) {
		this.id = id;
		this.client = client;
		this.nomprofil = nomprofil;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "cli_id", nullable = false)
	public Client getClient() {
		return this.client;
	}

	public void setClient(Client client) {
		this.client = client;
	}

	@Column(name = "nomprofil", length = 254)
	public String getNomprofil() {
		return this.nomprofil;
	}

	public void setNomprofil(String nomprofil) {
		this.nomprofil = nomprofil;
	}

}
