package models;
// Generated 15 mai 2022 15:03:36 by Hibernate Tools 3.6.0.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Recette generated by hbm2java
 */
@Entity
@Table(name = "recette", schema = "public")
public class Recette implements java.io.Serializable {

	private int id;
	private Rapport rapport;
	private Integer montantrecette;

	public Recette() {
	}

	public Recette(int id, Rapport rapport) {
		this.id = id;
		this.rapport = rapport;
	}

	public Recette(int id, Rapport rapport, Integer montantrecette) {
		this.id = id;
		this.rapport = rapport;
		this.montantrecette = montantrecette;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "rap_id", nullable = false)
	public Rapport getRapport() {
		return this.rapport;
	}

	public void setRapport(Rapport rapport) {
		this.rapport = rapport;
	}

	@Column(name = "montantrecette")
	public Integer getMontantrecette() {
		return this.montantrecette;
	}

	public void setMontantrecette(Integer montantrecette) {
		this.montantrecette = montantrecette;
	}

}
