package models;
// Generated 15 mai 2022 15:03:36 by Hibernate Tools 3.6.0.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Region generated by hbm2java
 */
@Entity
@Table(name = "region", schema = "public")
public class Region implements java.io.Serializable {

	private int id;
	private Pays pays;
	private String nomregion;
	private Set<Entreprise> entreprises = new HashSet<Entreprise>(0);

	public Region() {
	}

	public Region(int id, Pays pays) {
		this.id = id;
		this.pays = pays;
	}

	public Region(int id, Pays pays, String nomregion, Set<Entreprise> entreprises) {
		this.id = id;
		this.pays = pays;
		this.nomregion = nomregion;
		this.entreprises = entreprises;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "pay_id", nullable = false)
	public Pays getPays() {
		return this.pays;
	}

	public void setPays(Pays pays) {
		this.pays = pays;
	}

	@Column(name = "nomregion", length = 254)
	public String getNomregion() {
		return this.nomregion;
	}

	public void setNomregion(String nomregion) {
		this.nomregion = nomregion;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "region")
	public Set<Entreprise> getEntreprises() {
		return this.entreprises;
	}

	public void setEntreprises(Set<Entreprise> entreprises) {
		this.entreprises = entreprises;
	}

}
